slack:
  channel: '(Slack Channel ID)'
  token: '(Slack Token)'
  botname: '(Slack Bot ID)'

api:
  weather:
    cityid: '130010'

  wio:
    token: 'xxxxxxxxxxx'

  espr:
    url: 'http://esp8266.local/'
